from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


class PDFReport:

    def generate(
        self,
        filename,
        applicant_name,
        phone,
        purpose,
        age,
        income,
        loan_amount,
        interest_rate,
        loan_term,
        metrics,
        result,
        decision_summary
    ):

        doc = SimpleDocTemplate(filename)

        styles = getSampleStyleSheet()

        elements = []

        # TITLE

        elements.append(
            Paragraph(
                "<b><font size=20 color='blue'>CreditGuard AI</font></b>",
                styles["Title"]
            )
        )

        elements.append(
            Paragraph(
                "<b>AI Credit Risk Assessment Report</b>",
                styles["Heading2"]
            )
        )

        elements.append(Spacer(1, 20))

        # APPLICANT INFORMATION

        elements.append(
            Paragraph(
                "<b>Applicant Information</b>",
                styles["Heading2"]
            )
        )

        applicant_table = [

            ["Applicant Name", applicant_name],

            ["Phone", phone],

            ["Purpose", purpose],

            ["Age", str(age)]

        ]

        table = Table(applicant_table, colWidths=[180, 280])

        table.setStyle(TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 10)

        ]))

        elements.append(table)

        elements.append(Spacer(1, 20))

        # LOAN DETAILS

        elements.append(
            Paragraph(
                "<b>Loan Details</b>",
                styles["Heading2"]
            )
        )

        loan_table = [

            ["Annual Income", f"₹ {income:,.2f}"],

            ["Loan Amount", f"₹ {loan_amount:,.2f}"],

            ["Interest Rate", f"{interest_rate}%"],

            ["Loan Term", f"{loan_term} Months"],

            ["Monthly EMI", f"₹ {metrics['monthly_emi']:,.2f}"],

            ["Loan vs Income", f"{metrics['loan_vs_income']} x"],

            ["EMI Ratio", f"{metrics['emi_ratio']} %"]

        ]

        table = Table(loan_table, colWidths=[180, 280])

        table.setStyle(TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 0), (0, -1), colors.beige),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 10)

        ]))

        elements.append(table)

        elements.append(Spacer(1, 20))

        # AI RESULT

        elements.append(
            Paragraph(
                "<b>Prediction Result</b>",
                styles["Heading2"]
            )
        )

        result_table = [

            ["Decision", result["decision"]],

            ["Confidence", f"{result['confidence']} %"],

            ["Probability of Default", f"{result['probability']} %"],

            ["Risk Level", result["risk"]]

        ]

        table = Table(result_table, colWidths=[180, 280])

        table.setStyle(TableStyle([

            ("GRID", (0, 0), (-1, -1), 1, colors.grey),

            ("BACKGROUND", (0, 0), (0, -1), colors.lightgreen),

            ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 10)

        ]))

        elements.append(table)

        elements.append(Spacer(1, 20))

        # AI DECISION SUMMARY

        elements.append(
            Paragraph(
                "<b>AI Decision Summary</b>",
                styles["Heading2"]
            )
        )

        for item in decision_summary:

            elements.append(
                Paragraph(
                    f"✔ {item}",
                    styles["BodyText"]
                )
            )

        elements.append(Spacer(1, 20))

        # FOOTER

        elements.append(
            Paragraph(
                "<b>Generated by CreditGuard AI</b>",
                styles["Heading3"]
            )
        )

        elements.append(
            Paragraph(
                "Powered by LightGBM + Explainable AI",
                styles["BodyText"]
            )
        )

        doc.build(elements)

        return filename